#!/usr/bin/bash
if [ -z "$1" ]; then
        echo "Need argument (commit message)!" 1>&2
        exit 1
fi
ldoc -d . functions.lua
cd afterbirthplus.github.io
git add .
git commit -m "$1"
git push
cd ..
